export const statesAndUTs = [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
    'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland',
    'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttarakhand', 'Uttar Pradesh',
    'West Bengal', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Lakshadweep',
    'Delhi', 'Puducherry', 'Ladakh', 'Lakshadweep', 'Jammu and Kashmir'
];

// Mapping of states to their respective cities
export const citiesByState = {
    'Andhra Pradesh': ['Hyderabad', 'Visakhapatnam', 'Vijayawada'],
    'Arunachal Pradesh': ['Itanagar', 'Tawang', 'Ziro'],
    'Assam': ['Guwahati', 'Dibrugarh', 'Jorhat'],
    'Bihar': ['Patna', 'Gaya', 'Bhagalpur'],
    'Chhattisgarh': ['Raipur', 'Bilaspur', 'Durg'],
    'Goa': ['Panaji', 'Margao', 'Vasco da Gama'],
    'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara'],
    'Haryana': ['Chandigarh', 'Gurugram', 'Faridabad'],
    'Himachal Pradesh': ['Shimla', 'Manali', 'Kullu'],
    'Jharkhand': ['Ranchi', 'Jamshedpur', 'Dhanbad'],
    'Karnataka': ['Bengaluru', 'Mysuru', 'Mangalore'],
    'Kerala': ['Thiruvananthapuram', 'Kochi', 'Kozhikode'],
    'Madhya Pradesh': ['Bhopal', 'Indore', 'Gwalior'],
    'Maharashtra': ['Mumbai', 'Pune', 'Nagpur'],
    'Manipur': ['Imphal', 'Churachandpur', 'Thoubal'],
    'Meghalaya': ['Shillong', 'Tura', 'Jowai'],
    'Mizoram': ['Aizawl', 'Lunglei', 'Champhai'],
    'Nagaland': ['Kohima', 'Dimapur', 'Mokokchung'],
    'Odisha': ['Bhubaneswar', 'Cuttack', 'Berhampur'],
    'Punjab': ['Chandigarh', 'Amritsar', 'Ludhiana'],
    'Rajasthan': ['Jaipur', 'Udaipur', 'Kota'],
    'Sikkim': ['Gangtok', 'Pakyong', 'Namchi'],
    'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai'],
    'Telangana': ['Hyderabad', 'Warangal', 'Khammam'],
    'Tripura': ['Agartala', 'Udaipur', 'Dharmanagar'],
    'Uttarakhand': ['Dehradun', 'Nainital', 'Haridwar'],
    'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Varanasi'],
    'West Bengal': ['Kolkata', 'Darjeeling', 'Siliguri'],
    'Andaman and Nicobar Islands': ['Port Blair', 'Havelock Island', 'Diglipur'],
    'Chandigarh': ['Chandigarh'],
    'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa'],
    'Lakshadweep': ['Kavaratti', 'Agatti', 'Minicoy'],
    'Delhi': ['New Delhi', 'Dwarka', 'Lajpat Nagar'],
    'Puducherry': ['Puducherry', 'Auroville', 'Karai Kal'],
    'Ladakh': ['Leh', 'Kargil', 'Nubra Valley'],
    'Jammu and Kashmir': ['Srinagar', 'Jammu', 'Leh'],
};